"""Arm A diagnostics: WHY did the cross-region test null out, and is there a
within-region relationship that between-region variation was masking?

Context: ARM_A_CROSS_REGION_RETEST_2026-08-13.md retracted the n=6 headline.
Pooled rho for dissolved Fe fell to +0.056 (p=0.760) at n=31, and every
leave-one-region-out R2 was negative. Per-region signs split (Silverton/Ouray
positive; Central City/Creede/Leadville negative).

*** ON THE GEOLOGY HYPOTHESIS - READ BEFORE ADDING ONE ***
The "San Juan calderas behave differently" idea was generated by LOOKING AT
THESE SIGNS. Testing it on the same 31 catchments would be circular - the
grouping is fitted to the outcome. Any p-value from that test would be
meaningless, and this project has already been burned by exactly this error
twice (Test C's within-site thresholds, finding W1's tuned-until-it-worked
water indices). This module therefore DOES NOT test it and does not report a
p-value for it. What would actually test it: assign geology labels from a
published source for a set of regions chosen BEFORE looking at their signs
(pre-registration), or gather new regions and predict their sign in advance.

What this module DOES do, all non-circular:

  1. VARIANCE DECOMPOSITION. How much of the chemistry variance is BETWEEN
     regions vs WITHIN them? If most is between, a pooled correlation is
     mostly comparing river systems to each other (geology, climate,
     precipitation, mine history) rather than testing whether more upstream
     AMD area means more downstream metal. That would make the pooled null
     an answer to the wrong question.

  2. WITHIN-REGION CORRELATION - the analysis that should have been run
     first. Rank x and y WITHIN each region, centre those ranks, pool, and
     correlate. This removes every between-region difference by construction
     and asks the mechanistically meaningful question: within one river
     system, do catchments with more AMD area carry more dissolved Fe?
     Significance via permutation that shuffles y WITHIN region only, so the
     region structure is preserved under the null.

  3. DYNAMIC-RANGE SCREEN. A per-region rho is uninterpretable if that
     region's chemistry barely varies. Alma spans 0.033-0.037 mg/L dissolved
     Fe across its 3 catchments; a correlation there is noise by
     construction, and pooling it in as if it were evidence is misleading.

  4. CATCHMENT-AREA CONFOUND. Fe concentration at an outlet is roughly
     load/discharge; load scales with absolute AMD area and discharge with
     catchment area, so AMD *fraction* (M1) is dimensionally the right
     predictor. But precipitation is not uniform and Fe precipitates out with
     transport distance, so area can still confound. Reported as a partial
     (rank) correlation controlling for area.

    .venv/Scripts/python python/arma_diagnostics.py
"""

import argparse
import glob
import os

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATCHED_DIR = os.path.join(ROOT, "data", "matched")
CHEM_VARS = ["Iron_mgL_dissolved", "Iron_mgL_any", "Sulfate_mgL", "pH",
            "SpecificConductance"]
LOADINGS = [("ours_m1", "ours M1 (AMD%)"), ("ours_m2", "ours M2 (NAP-w)"),
           ("rockwell_m1", "rockwell M1"), ("rockwell_m2", "rockwell M2")]
MIN_REGION_N = 3


def load_all(pattern="watershed_nap_*.csv"):
    frames = []
    for p in sorted(glob.glob(os.path.join(MATCHED_DIR, pattern))):
        d = pd.read_csv(p)
        if "region" not in d.columns:
            d["region"] = os.path.basename(p).replace(
                "watershed_nap_", "").replace(".csv", "")
        frames.append(d)
    if not frames:
        raise SystemExit("no watershed_nap_*.csv in %s" % MATCHED_DIR)
    return pd.concat(frames, ignore_index=True).drop_duplicates(
        subset=["region", "basin_id"])


def _rank(a):
    a = np.asarray(a, float)
    order = np.argsort(a, kind="mergesort")
    r = np.empty(len(a), float)
    r[order] = np.arange(1, len(a) + 1)
    s = a[order]
    rr = r[order]
    i = 0
    while i < len(s):
        j = i
        while j + 1 < len(s) and s[j + 1] == s[i]:
            j += 1
        if j > i:
            rr[i:j + 1] = rr[i:j + 1].mean()
        i = j + 1
    r[order] = rr
    return r


def spearman(x, y):
    x, y = np.asarray(x, float), np.asarray(y, float)
    m = ~(np.isnan(x) | np.isnan(y))
    x, y = x[m], y[m]
    if len(x) < 4:
        return float("nan"), len(x)
    rx, ry = _rank(x), _rank(y)
    if rx.std() == 0 or ry.std() == 0:
        return float("nan"), len(x)
    return float(np.corrcoef(rx, ry)[0, 1]), len(x)


def variance_decomposition(d, var):
    """Return (between_frac, within_frac, n, n_regions) for `var`.

    Uses the classic one-way ANOVA split on ranks (rank-based so it matches
    the Spearman analyses and is robust to the heavy skew in Fe).
    """
    sub = d[[var, "region"]].dropna()
    if len(sub) < 6 or sub.region.nunique() < 2:
        return float("nan"), float("nan"), len(sub), sub.region.nunique()
    vals = _rank(sub[var].to_numpy())
    grand = vals.mean()
    ss_total = ((vals - grand) ** 2).sum()
    if ss_total == 0:
        return float("nan"), float("nan"), len(sub), sub.region.nunique()
    ss_between = 0.0
    for _, idx in sub.groupby("region").groups.items():
        pos = sub.index.get_indexer(idx)
        g = vals[pos]
        ss_between += len(g) * (g.mean() - grand) ** 2
    return (ss_between / ss_total, 1 - ss_between / ss_total,
            len(sub), sub.region.nunique())


def within_region_corr(d, xcol, ycol, min_n=MIN_REGION_N):
    """Correlation of WITHIN-region centred ranks, pooled across regions.

    Ranks are computed inside each region and then mean-centred, so every
    between-region difference (geology, climate, mine history, scene
    availability) is removed by construction. Regions with fewer than min_n
    usable catchments are dropped - they cannot contribute a meaningful
    within-region rank.
    """
    sub = d[[xcol, ycol, "region"]].dropna()
    xs, ys, kept = [], [], []
    for reg, g in sub.groupby("region"):
        if len(g) < min_n:
            continue
        rx = _rank(g[xcol].to_numpy())
        ry = _rank(g[ycol].to_numpy())
        if rx.std() == 0 or ry.std() == 0:
            continue
        xs.append(rx - rx.mean())
        ys.append(ry - ry.mean())
        kept.append(reg)
    if len(kept) < 2:
        return float("nan"), 0, 0, kept
    x = np.concatenate(xs)
    y = np.concatenate(ys)
    if x.std() == 0 or y.std() == 0:
        return float("nan"), len(x), len(kept), kept
    return float(np.corrcoef(x, y)[0, 1]), len(x), len(kept), kept


def within_region_perm_p(d, xcol, ycol, n_perm=20000, seed=0,
                         min_n=MIN_REGION_N):
    """Permutation p for the within-region correlation, shuffling y ONLY
    inside each region so the region structure is preserved under the null."""
    sub = d[[xcol, ycol, "region"]].dropna()
    groups = [(g[xcol].to_numpy(), g[ycol].to_numpy())
             for _, g in sub.groupby("region") if len(g) >= min_n]
    groups = [(x, y) for x, y in groups
             if _rank(x).std() > 0 and _rank(y).std() > 0]
    if len(groups) < 2:
        return float("nan")

    def pooled(gs):
        xs, ys = [], []
        for x, y in gs:
            rx, ry = _rank(x), _rank(y)
            xs.append(rx - rx.mean())
            ys.append(ry - ry.mean())
        X, Y = np.concatenate(xs), np.concatenate(ys)
        if X.std() == 0 or Y.std() == 0:
            return float("nan")
        return float(np.corrcoef(X, Y)[0, 1])

    obs = pooled(groups)
    if np.isnan(obs):
        return float("nan")
    rng = np.random.default_rng(seed)
    hits = 0
    for _ in range(n_perm):
        shuffled = [(x, rng.permutation(y)) for x, y in groups]
        r = pooled(shuffled)
        if not np.isnan(r) and abs(r) >= abs(obs):
            hits += 1
    return hits / n_perm


def partial_spearman(d, xcol, ycol, ctrl):
    """Rank partial correlation of x,y controlling for ctrl."""
    sub = d[[xcol, ycol, ctrl]].dropna()
    if len(sub) < 6:
        return float("nan"), len(sub)
    rx, ry, rc = (_rank(sub[xcol].to_numpy()), _rank(sub[ycol].to_numpy()),
                 _rank(sub[ctrl].to_numpy()))
    if rx.std() == 0 or ry.std() == 0 or rc.std() == 0:
        return float("nan"), len(sub)
    rxy = np.corrcoef(rx, ry)[0, 1]
    rxc = np.corrcoef(rx, rc)[0, 1]
    ryc = np.corrcoef(ry, rc)[0, 1]
    denom = np.sqrt((1 - rxc ** 2) * (1 - ryc ** 2))
    if denom == 0:
        return float("nan"), len(sub)
    return float((rxy - rxc * ryc) / denom), len(sub)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--n-perm", type=int, default=20000)
    args = ap.parse_args(argv)

    d = load_all()
    print("%d catchments, %d regions: %s"
          % (len(d), d.region.nunique(), ", ".join(sorted(d.region.unique()))))

    print("\n" + "=" * 92)
    print("3. DYNAMIC-RANGE SCREEN - which regions can even support a correlation?")
    print("=" * 92)
    print("  %-20s %4s %22s %22s" % ("region", "n", "dissolved Fe range", "AMD% range"))
    thin = []
    for reg, g in d.groupby("region"):
        fe = g.Iron_mgL_dissolved.dropna()
        fe_rng = (fe.max() - fe.min()) if len(fe) else float("nan")
        amd_rng = g.ours_m1.max() - g.ours_m1.min()
        flag = ""
        if len(fe) and fe_rng < 0.05:
            flag = "  <- Fe barely varies; rho here is noise"
            thin.append(reg)
        print("  %-20s %4d %10.3f-%-10.3f %10.3f-%-10.3f%s"
              % (reg, len(g), fe.min() if len(fe) else float("nan"),
                 fe.max() if len(fe) else float("nan"),
                 g.ours_m1.min(), g.ours_m1.max(), flag))
    if thin:
        print("\n  %d region(s) flagged: %s" % (len(thin), ", ".join(thin)))
        print("  Their per-region rho values in the retest report should NOT be\n"
              "  read as evidence of a positive or negative relationship.")

    print("\n" + "=" * 92)
    print("1. VARIANCE DECOMPOSITION - is a pooled correlation even asking the right question?")
    print("=" * 92)
    print("  %-24s %8s %10s %10s %8s" % ("chemistry var", "n", "BETWEEN%", "WITHIN%", "regions"))
    for var in CHEM_VARS:
        if var not in d.columns:
            continue
        btw, wth, n, nreg = variance_decomposition(d, var)
        if np.isnan(btw):
            continue
        print("  %-24s %8d %9.1f%% %9.1f%% %8d" % (var, n, 100 * btw, 100 * wth, nreg))
    print("\n  A high BETWEEN%% means the pooled rho is mostly comparing river\n"
          "  systems to one another - geology, climate, precipitation, mining\n"
          "  history - rather than testing the loading relationship itself.")

    print("\n" + "=" * 92)
    print("2. WITHIN-REGION CORRELATION - the non-circular test (region effects removed)")
    print("=" * 92)
    print("  %-24s %-16s %6s %7s %8s %8s"
          % ("chemistry var", "loading", "n", "regions", "rho_within", "perm_p"))
    tests = []
    for var in CHEM_VARS:
        if var not in d.columns:
            continue
        any_row = False
        for key, label in LOADINGS:
            if key not in d.columns:
                continue
            rho, n, nreg, kept = within_region_corr(d, key, var)
            if np.isnan(rho):
                continue
            p = within_region_perm_p(d, key, var, args.n_perm)
            tests.append((p, var, label, rho, n))
            print("  %-24s %-16s %6d %7d %+8.3f %8.3f"
                  % (var, label, n, nreg, rho, p))
            any_row = True
        if any_row:
            print()

    # Multiple-comparison correction. 20 tests at uncorrected alpha=0.05 gives
    # ~1 expected false positive, so an isolated p<0.05 here is exactly what
    # chance produces - the same trap the pooled analysis fell into.
    if tests:
        print("  --- multiple-comparison correction (%d tests) ---" % len(tests))
        m = len(tests)
        ranked = sorted(tests, key=lambda t: t[0])
        bonf_alpha = 0.05 / m
        any_survive = False
        for i, (p, var, label, rho, n) in enumerate(ranked[:5], 1):
            bh_thresh = 0.05 * i / m
            bh_ok = p <= bh_thresh
            bonf_ok = p <= bonf_alpha
            if bh_ok or bonf_ok:
                any_survive = True
            print("    %-24s %-16s rho=%+.3f p=%.3f  BH_thresh=%.4f %s"
                  % (var, label, rho, p, bh_thresh,
                     "SURVIVES" if bh_ok else "fails BH"))
        print("    Bonferroni alpha = %.4f" % bonf_alpha)
        if not any_survive:
            print("    NOTHING survives correction. Any p<0.05 above is within\n"
                  "    what %d tests produce by chance and must be treated as a\n"
                  "    lead to test on new data, NOT as a finding." % m)

    print("=" * 92)
    print("4. CATCHMENT-AREA CONFOUND (pooled rank partial correlation)")
    print("=" * 92)
    r_area_fe, n1 = spearman(d.area_km2, d.Iron_mgL_dissolved)
    r_area_amd, n2 = spearman(d.area_km2, d.ours_m1)
    print("  area_km2 vs dissolved Fe : rho=%+.3f (n=%d)" % (r_area_fe, n1))
    print("  area_km2 vs ours M1      : rho=%+.3f (n=%d)" % (r_area_amd, n2))
    print()
    print("  %-24s %-16s %8s %10s %12s"
          % ("chemistry var", "loading", "n", "rho_raw", "rho|area"))
    for var in CHEM_VARS:
        if var not in d.columns:
            continue
        for key, label in LOADINGS:
            if key not in d.columns:
                continue
            raw, _ = spearman(d[key], d[var])
            par, n = partial_spearman(d, key, var, "area_km2")
            if np.isnan(raw) or np.isnan(par):
                continue
            print("  %-24s %-16s %8d %+10.3f %+12.3f" % (var, label, n, raw, par))
        print()

    print("-" * 92)
    print("The geology hypothesis is NOT tested here and deliberately has no\n"
          "p-value: it was generated by looking at these same signs, so testing\n"
          "it on this data would be circular. See the module docstring for what\n"
          "would actually test it.")


if __name__ == "__main__":
    main()
